name: learn-github-action
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: setup prerequisites
          run: |
            sudo apt update
            sudo apt install build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget
        
        - name: download openwrt sdk
          run: |
            mkdir ./mywork
            cd ./mywork
            wget https://archive.openwrt.org/releases/23.05.2/targets/ramips/mt7620/openwrt-sdk-23.05.2-ramips-mt7620_gcc-12.3.0_musl.Linux-x86_64.tar.xz
            # tar xf openwrt-sdk-23.05.2-ramips-mt7620_gcc-12.3.0_musl.Linux-x86_64.tar.xz -C openwrt-sdk-23.05.2
            tar xf openwrt-sdk-23.05.2-ramips-mt7620_gcc-12.3.0_musl.Linux-x86_64.tar.xz
            mv openwrt-sdk-23.05.2-ramips-mt7620_gcc-12.3.0_musl.Linux-x86_64 openwrt-sdk-23.05.2
            cd openwrt-sdk-23.05.2
            make defconfig
            ls -l .config
            cat .config

        - name: clone openclash
          run: |
            mkdir package/luci-app-openclash
            cd package/luci-app-openclash
            git init
            git remote add -f origin https://github.com/vernesong/OpenClash.git
            git config core.sparsecheckout true
            echo "luci-app-openclash" >> .git/info/sparse-checkout
            git pull --depth 1 origin master
            git branch --set-upstream-to=origin/master master
            
            # 编译 po2lmo (如果有po2lmo可跳过)
            pushd luci-app-openclash/tools/po2lmo
            make && sudo make install
            popd
            
            # 开始编译
            # 先回退到SDK主目录
            cd ../..
            # make package/feeds/luci/luci-base/compile V=s
            make package/luci-app-openclash/luci-app-openclash/compile V=99
            mkdir -p ./artifact/myipk
            cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/myipk/
          working-directory: ./mywork
        
        - name: Upload ipk
          uses: actions/upload-artifact@v3
          with:
            name: luci-app-openclash
            path: ./artifact/myipk
